// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_dart/firebase_dart.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBujy5VtHYtgd_mVxaJ_Kav_Myg0mNrjI8',
    appId: '1:928662382569:web:31443ebd4e33c303a04d78',
    messagingSenderId: '928662382569',
    projectId: 'part3-29031',
    authDomain: 'part3-29031.firebaseapp.com',
    storageBucket: 'part3-29031.firebasestorage.app',
    measurementId: 'G-1V0FTNT573',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3X5DC5Z3XjxoZfdEGQj-wX2wZ0JBzdeg',
    appId: '1:928662382569:android:64d7816d582db835a04d78',
    messagingSenderId: '928662382569',
    projectId: 'part3-29031',
    storageBucket: 'part3-29031.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBCy6VtNCLr1m1OmXFXp3SGv5jOK90rkM',
    appId: '1:928662382569:ios:7b202e3c1df19725a04d78',
    messagingSenderId: '928662382569',
    projectId: 'part3-29031',
    storageBucket: 'part3-29031.firebasestorage.app',
    iosBundleId: 'com.example.flutterTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBCy6VtNCLr1m1OmXFXp3SGv5jOK90rkM',
    appId: '1:928662382569:ios:7b202e3c1df19725a04d78',
    messagingSenderId: '928662382569',
    projectId: 'part3-29031',
    storageBucket: 'part3-29031.firebasestorage.app',
    iosBundleId: 'com.example.flutterTemplate',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyC3X5DC5Z3XjxoZfdEGQj-wX2wZ0JBzdeg',
    appId: '1:928662382569:android:64d7816d582db835a04d78',
    messagingSenderId: '928662382569',
    projectId: 'part3-29031',
    storageBucket: 'part3-29031.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBujy5VtHYtgd_mVxaJ_Kav_Myg0mNrjI8',
    appId: '1:928662382569:web:3fcc85c36086dab7a04d78',
    messagingSenderId: '928662382569',
    projectId: 'part3-29031',
    authDomain: 'part3-29031.firebaseapp.com',
    storageBucket: 'part3-29031.firebasestorage.app',
    measurementId: 'G-4JP33F6TCE',
  );
}
